### ISSUE TITLE
快捷启动的遐想

### ISSUE THREAD

**Issue by itldg** [iamxiyang/utools-random-data#14]
我们做站点开发,会测试添加账号,姓名,手机号等字段是必填的

我将这些字段都打开了快捷启动,但是依然需要唤醒uTools,输入`姓名`,选择插件,过程比较多

如果直接用鼠标快捷键唤醒超级面板,我将这些常用的随机指令都钉在面板中,快了很多

![image](https://github.com/user-attachments/assets/517c8f6d-faac-4e62-8581-8decc5f026c4)

但是如果某些插件识别了进程名

![image](https://github.com/user-attachments/assets/6a00e18c-6e48-4aa0-9ee9-e6e439428b71)

就会让操作变得麻烦起来,用之前要先禁用其它插件,再使用随机指令

有没有可能让随机指令的某些指令也这样可以添加某些进程,让操作再快一步?

参考快捷指令

![image](https://github.com/user-attachments/assets/c5698785-881c-4905-b325-e801868e1a69)

**Comment by iamxiyang** [comment]
我测了一下 utools 5.2.0 ，在网页中操作时能够直接看到全部固定的指令，不需要禁用其它插件。你升级到最新版试一下满足不满足需求呢

![image](https://github.com/user-attachments/assets/279eaa46-ee09-4460-9544-0de44768bbbd)

![image](https://github.com/user-attachments/assets/6a4a9ec7-c5ea-4d19-8018-55a7ccac5f8e)
