### ISSUE TITLE
定义新指令的时候生成出错，JSON模板的形式

### ISSUE THREAD

**Issue by TaroXin** [iamxiyang/utools-random-data#4]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/19855713/211248696-2e016ab5-dbef-4aef-b70b-125e60242183.png">

模板是这样
```json
{"accountType":1,"username":"${时间戳}","mobile":"${手机号}","email":"${邮箱}","roleIdList":[2],"isSecondConfirm":true,"deptId":120,"id":null}
```

生成结果
<img width="800" alt="image" src="https://user-images.githubusercontent.com/19855713/211248857-ba9da874-33c3-47ef-a941-5539ad39ea0e.png">

**Comment by iamxiyang** [comment]
1.3.1 版本已处理
